services:
  elastic:
    image: elasticsearch:8.13.4
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/dat
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: kibana:8.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200    # address of elasticsearch docker container which kibana will connect
    ports:
      - 5601:5601
    depends_on:
      - elastic